name: jwx_flutter
description: 易知课堂Flutter版.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  provider: ^5.0.0
  dio: ^4.0.0
  fluro: ^2.0.3
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  path: ^1.8.0
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  json_annotation: ^3.1.1
  flushbar: ^1.10.4

  # 私有Package引入  使用ref选择分支或tag
  jhk_extension:
    git:
      url: git@github.com:jia-hisense/jhk_extension.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - images/background.png

flutter_intl:
  main_locale: en_US
  enabled: true
